### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by HuuNguyen312** [panwrona/Workcation#2]
This is Error Log:

```
03-13 10:52:33.715 29549-29549/com.droidsonroids.workcation E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.droidsonroids.workcation, PID: 29549
                                                                              java.lang.IllegalArgumentException: radius must be > 0
                                                                                  at android.graphics.RadialGradient.<init>(RadialGradient.java:57)
                                                                                  at android.graphics.drawable.GradientDrawable.ensureValidRect(GradientDrawable.java:938)
                                                                                  at android.graphics.drawable.GradientDrawable.draw(GradientDrawable.java:509)
                                                                                  at android.view.View.getDrawableRenderNode(View.java:15677)
                                                                                  at android.view.View.drawBackground(View.java:15625)
                                                                                  at android.view.View.draw(View.java:15348)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14254)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.draw(View.java:15376)
                                                                                  at android.widget.FrameLayout.draw(FrameLayout.java:652)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14254)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14246)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14246)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.draw(View.java:15376)
                                                                                  at android.widget.FrameLayout.draw(FrameLayout.java:652)
                                                                                  at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1768)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14254)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1223)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14246)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14246)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.draw(View.java:15376)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14254)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1223)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14246)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14246)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3533)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3327)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14246)
                                                                                  at android.view.View.getDisplayList(View.java:14284)
                                                                                  at android.view.View.draw(View.java:15069)
                                                                              	at android.view.ViewGroup.drawChild(ViewGroup.java:353
```

**Comment by HuuNguyen312** [comment]
I solved this problem:
**Replace** `android:gradientRadius="xx%"` to `android:gradientRadius="xx%p"`
