### ISSUE TITLE
Sample is very different than the gif in the repo

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [panwrona/Workcation#3]
It looks like this:
![image](https://cloud.githubusercontent.com/assets/5357526/24898453/aabdc598-1ea5-11e7-9610-fc19b27c75e3.png)

Plus, when pressing the bottom tab, it crashes:

04-11 10:56:04.706 7293-7293/com.droidsonroids.workcation E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.droidsonroids.workcation, PID: 7293
                                                                            java.lang.NullPointerException: Attempt to read from field 'java.util.Map android.transition.TransitionValues.values' on a null object reference
                                                                                at com.droidsonroids.workcation.common.transitions.ScaleDownImageTransition.createAnimator(ScaleDownImageTransition.java:66)
                                                                                at android.transition.Transition.createAnimators(Transition.java:732)
                                                                                at android.transition.TransitionSet.createAnimators(TransitionSet.java:396)
                                                                                at android.transition.Transition.playTransition(Transition.java:1777)
                                                                                at android.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:306)
                                                                                at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by panwrona** [comment]
The main screen of the map is not finished, however the main purpose was to create the animations in DetailsFragment to be as close as possible to the gif. I can add the blur search in the AppBar and horizontal RecyclerView if you want. But it's just that

**Comment by panwrona** [comment]
And about the crash, I will look into it closely

**Comment by amrro** [comment]
I turned around that using: 
```
if (startValues != null) {
                float scaleX = (float)startValues.values.get(PROPNAME_SCALE_X);
                float scaleY = (float)startValues.values.get(PROPNAME_SCALE_Y);

            }
```

**Comment by panwrona** [comment]
And that's the case! Sorry for late response, maybe You want to add PR? @amrro
